on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    name: AWS Secret
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: echo "Hello"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
        aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
        role-duration-seconds: 1
    - name: Sleep
      run: sleep 5
    - name: Run Aws region command
      run: |
        aws configure list | grep region | awk '{print $2}'
    - name: Step name
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          test_secret_in_Harness
